### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by joeandaverde** [lob/fluent-plugin-json-transform#1]
Can you post an example of your entire fluentd configuration?

I have an interest on seeing how to get custom fields to show up in elastic search. Currently, the log messages look something like this:

```json
{
 "log":"{ \"message\": \"the log message\", \"extra\": { \"foo\": 1, \"bar\": 200 } }", 
 "stream":"stderr", 
 "time":"2014-09-25T21:15:03.499185026Z"
}
```

Notice how the log property contains a JSON object. I'd like to flatten that out and add to output for elastic search.

**Comment by mgartner** [comment]
Closing. Please see https://github.com/mjourard/fluent-plugin-json-transform.
