### ISSUE TITLE
fails with both "flatten" and "nothing" on fluentd 0.12.22

### ISSUE THREAD

**Issue by stensonb** [lob/fluent-plugin-json-transform#2]
```
$> cat fluentd.conf
<source>
  type http
  format json_transform
  transform_script flatten
  port 8888
  bind 0.0.0.0
</source>

<match **>
  @type stdout
</match>
```

```
curl http://localhost:8888 -d 'json={"msg":"hi"}'
400 Bad Request
undefined method `parse' for #<Fluent::TextParser::JSONTransformParser:0x007feaa2161ba8>
```

```
$> cat fluentd.conf
<source>
  type http
  format json_transform
  transform_script nothing
  port 8888
  bind 0.0.0.0
</source>

<match **>
  @type stdout
</match>
```

```
curl http://localhost:8888 -d 'json={"msg":"hi"}'
400 Bad Request
undefined method `parse' for #<Fluent::TextParser::JSONTransformParser:0x007fdd8d0ee260>
```

**Comment by mjourard** [comment]
If anybody else is trying to fix this, it appears at some point the TextParser class changed from calling the 'call' method to calling a 'parse' method. 

In the file /lib/fluent/plugin/parser_json_transform.rb, changing the line 'def call(text)' to 'def parse(text)' 
gets rid of the error.

 $> cat /etc/td-agent/td-agent.conf
<source>
  type http
  format adk_json_transform
  transform_script flatten
  port 8888
  bind 0.0.0.0
</source>

<match **>
  @type file
  path /var/log/td-agent/json_transformer_testing/output
</match>

curl http://localhost:8888 -d '{"msg":{"salutation":"hi","question":"how are you?"}}'

tail /var/log/td-agent/json_transformer_testing/output.20160415.b5308aee793b5b361
2016-04-15T19:23:42+00:00               {"msg.salutation":"hi","msg.question":"how are you?"}

**Comment by mgartner** [comment]
Closing. Please see https://github.com/mjourard/fluent-plugin-json-transform.
